data:
  lookback_days: 7        # cuántos días intradía (1m) descargamos por ticker
  interval: "1m"          # marco temporal

strategy:
  horizon: 10             # mantener la posición máx 10 velas (~10 minutos)
  tp: 0.007               # +0.7% take profit (0.7% expresado como decimal)
  sl: 0.0025              # -0.25% stop loss (0.25% expresado como decimal)

  base_prob_threshold: 0.6   # umbral base de probabilidad BUY para abrir trade
  capital: 10000             # capital inicial simulado en el backtest (USD)
  risk_fraction: 0.01        # % del capital que arriesgas por trade (1%)

features:
  include:
    - close
    - high
    - low
    - open
    - volume
    - return_1m
    - return_5m
    - vwap_dist
    - rsi_14
    - vol_zscore
    - range_ratio
    - above_open        # precio actual por encima de la apertura del día? (0/1)
    - day_return        # % que lleva el ticker hoy vs apertura
    - rolling_volatility_5
    - rolling_volatility_15
    - liquidity_score   # volumen normalizado intradía / liquidez contexto

model:
  n_estimators: 200
  learning_rate: 0.05
  max_depth: 5
  subsample: 0.9
  colsample_bytree: 0.9
  test_split_ratio: 0.2
  random_state: 42
